version: 2.1

machine:
  services:
    - docker

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "{{cookiecutter.project_slug}}/backend/requirements.txt" }}
            - deps1-{{ .Branch }}-{{ checksum "{{cookiecutter.project_slug}}/frontend/package.json" }}
            - deps1-{{ .Branch }}-{{ checksum "{{cookiecutter.project_slug}}/docker-compose.yml" }}
      - run:
          command: sudo pip install cookiecutter
      - run:
          command: ./scripts/build.sh
          name: build
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "{{cookiecutter.project_slug}}/backend/requirements.txt" }}
          paths:
            - /home/circleci/.local/bin/
      - run:
          command: ./scripts/test.sh
          name: Test
          environment:
            CIRCLE_CI_ENV: true

workflows:
  main:
    jobs:
      - build-and-test
